### ISSUE TITLE
Create an Amazon instance for the Genomics Data Carpentry

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/cloud-genomics#1]
Create an Amazon instance with the the environment set up for a Genomics Data Carpentry workshop

**Comment by souravsingh** [comment]
I would like to work on this. Is there anything i need to know?

**Comment by tracykteal** [comment]
We actually have one already. I should have updated this issue. The instance is 

ami-6516b30e

Information on launching the instance
https://github.com/JasonJWilliamsNY/cloud-genomics/blob/master/lessons/1.logging-onto-cloud.md

We have it set up so that once it's spun up, people can ssh in with a set username and password. 

It would be great if you wanted to spin one up and see if you had any comments.

**Comment by mkuzak** [comment]
Is there any documentation about whats installed in the vm?

**Comment by devbioinfoguy** [comment]
I can post an additional document that will list the filetree at high level.
