### ISSUE TITLE
Fix javascript for selecting type of cloud computing being used

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/cloud-genomics#1]
In this lesson, people may want to use different cloud resources for login, for example, Amazon AWS, CyVerse Atmosphere or a local HPC. 

We're trying out some javascript so that on the 'logging onto the cloud' page people can select what type of cloud computing they're using, so they have those directions. That's still in development, so that's why so many 'introduction' pages appear.

We need to fix the Javascript or just have a static list of types of compute that can link to the appropriate pages.

**Comment by ACharbonneau** [comment]
#Fixed
