### ISSUE TITLE
Update maintainer list in README

### ISSUE THREAD

**Issue by ACharbonneau** [datacarpentry/cloud-genomics#101]
I think we should consider updating our README to look more like the one for [wrangling](https://github.com/datacarpentry/wrangling-genomics) with an explicit list of maintainers at the top so it's easier to figure out who to contact. 

Right now there's a "contributor list", but it's actually the list of people from the original cloud workgroup from the retreat where we started writing the genomics workshop and none of them are still active on this lesson, so it's a little confusing. Maybe we should come up with a better term for them than 'contributor' that distinguishes them from the really big list of people who've contributed to the lesson at this point.

**Comment by shukwong** [comment]
I totally agree!
How about something like, "This lesson was first developed by <list of people> and is currently maintained by <list of people>" ?

**Comment by ACharbonneau** [comment]
I like that :)

**Comment by anwarMZ** [comment]
Maintainer list was updated.
