### ISSUE TITLE
Merge "Logging on" and "Why of cloud computing"?

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/cloud-genomics#11]
At the moment, the two pages/sections are actually covering the same thing: logging onto a remote server and using it. 

Should they be merged so that we have one page?

**Comment by dvanic** [comment]
Also, we have the [Connecting to a remote instance](http://www.datacarpentry.org/cloud-genomics/beta-03-connecting-to-remote-issue/) as well - should that also be merged???

**Comment by ACharbonneau** [comment]
I think we should merge them all into "Logging on" and add a short "why" into the introduction
