### ISSUE TITLE
Introuducing FASTQ format and error profiles

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/cloud-genomics#13]
[link](http://www.datacarpentry.org/cloud-genomics/beta-04-data-to-from-instance/)
This section actually duplicates the moving files section, and DOES NOT at all touch on FASTQ formats or error profiles.

**Comment by devbioinfoguy** [comment]
This section should likely be removed. Moving files section is more important, and FASTQ format is described in a different lesson (knowing your data?).

**Comment by ACharbonneau** [comment]
Unfortunately today is my heavy teaching day, so I can't be on much. But I have a list of things I think we need to add and drop in the google doc that Tracy was working on a couple weeks ago... https://docs.google.com/document/d/1BSjauNddxjI5w1EjKcB_vcQaG9y4okYY3rCQsD4rC3s/edit#heading=h.l7jkbo5mfbn

**Comment by ACharbonneau** [comment]
Closing, redundant with discussion at https://github.com/datacarpentry/cloud-genomics/issues/19
