### ISSUE TITLE
Merge single analysis 1 and 2

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/cloud-genomics#14]
Single analysis (version 2) is duplicating material from Single analysis version 1

[version 1](http://www.datacarpentry.org/cloud-genomics/04-single-analysis/)
[version 2](http://www.datacarpentry.org/cloud-genomics/beta-06-single-analysis/) 

Should we merge the two???

**Comment by devbioinfoguy** [comment]
I'm not sure this module and the parallel one belong here anymore. IMHO these should be retired. This information is covered in the analysis lessons. Instead, if we wish to keep something related to serial vs parallel, we could demonstrate an example serial run vs parallel (parallel within one program & using gnu parallel) and show the time savings.

**Comment by ACharbonneau** [comment]
Seconded. These analyses are redundant with other lessons, and should just be dropped, but the demo is a good idea. 
Actually, this issue is redundant with 19, I'm closing it and bumping the discussion to there. https://github.com/datacarpentry/cloud-genomics/issues/19
