### ISSUE TITLE
Single analysis

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/cloud-genomics#15]
[Single analysis](http://www.datacarpentry.org/cloud-genomics/04-single-analysis/) and [version 2](http://www.datacarpentry.org/cloud-genomics/beta-06-single-analysis/) 

- [ ] Add learning objectives and questions
- [ ] This section assumes we're using AWS and AMI. Add/edit content to reflect that we could be using university HPC or CyVerse
- [ ] Fix link to logging onto a cloud instance from "http://www.datacarpentry.org/cloud-genomics/1.logging-onto-cloud.md"
- [ ] Add key points
- [ ] Fix image links

**Comment by devbioinfoguy** [comment]
See my comments on #14 (I don't think we need this as is anymore)

**Comment by ACharbonneau** [comment]
Closing. Redundant with discussion at https://github.com/datacarpentry/cloud-genomics/issues/19
