### ISSUE TITLE
Add instructor notes document for this lesson

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/cloud-genomics#16]
I'm working on helping direct instructor attention towards fixing up/contributing to instructor notes. Currently don't have a link to provide for instructor notes for this lesson. Please add - even a blank document would be somewhere to point towards.

**Comment by devbioinfoguy** [comment]
Erin, there is an Instructor's notes doc at https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/InstructorNotes.md. Is there something beyond this you are thinking about?

**Comment by ErinBecker** [comment]
@devbioinfoguy Thanks Bob. For some reason I didn't see that doc.
