### ISSUE TITLE
typos [datacarpentry/shell-genomics#28]

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/cloud-genomics#18]
From Asli Uyar, see datacarpentry/shell-genomics#28

https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/lessons/1.logging-onto-cloud.md:

    "We will cover as much as we you need to get through the Data Carpentry lessons”

https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/lessons/4.parallel-analysis.md:

    "And you computer does each execution in order”
    "But what if you do'nt have enough cores to match the number of programs run?”
    "What commands can use you to see your process IDs?”

**Comment by devbioinfoguy** [comment]
Sorry, posted in wrong lesson. I'll review these this afternoon. Thanks!
