### ISSUE TITLE
Serial vs Parallel Computing

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [datacarpentry/cloud-genomics#19]
Hi there,

I've just been working through the "Single analysis" lesson, 
albeit carrying out the FastQC run on the HPC facility that 
I adminster here (as that's where I've installed all the software
for our BiInformaticians).

I note that the current (github,io) rendering of the lesson,
the FastQC results page section

```
Interpreting FastQC results

Let’s have a look at the results. This is the boxplot analysis for your FASTQ data.
Phred quality score is on the ordinate axis. The purpose of this plot is to look at
the overall quality of the sequence.

Before Trimming

This indicates very poor quality toward the end of the reads. You can also look 
at lots of other quality issues, including potential adapter contamination, and 
over-represented kmers near the beginning of the read. 
Contrast this to a good sequencing run.
```
doesn't have a link to an HTML file, with the lesson's results, although there is
a link to an external one in the link behind `good sequencing run` in the above,
which takes the person reading the lesson out to 

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/good_sequence_short_fastqc.html

Two issues then:

1. What's the plan, in terms of displaying the lesson's HTML page
2. Is it a good idea to rely on sending people outside of the lesson
    in order to see content

My suggestions would be to either render the HTML content locally, 
that is within the lesson, so that it is self-contained, or to replace the
HTML with some screen-grabbed images of the HTML page's content.

The benefit of the latter approach, on top of being self-contained, is that 
what we are showing to people are just simple images, which are then
capable of being annotated should that be useful.

I'm about to try and knock up something that i can make visible to you
that might demonstrate such an approach, and will add to the issue 
commentary in due course, but wanted to get the idea, as regards 
screen-grabbing the HTML, into the list of things for consideration,
ahead of any release of the lesson.

Kevin M. Buckley

eScience Consultant
School of Engineering and Computer Science
Victoria University of Wellington
New Zealand

**Comment by vuw-ecs-kevin** [comment]
Take a look at 

http://homepages.ecs.vuw.ac.nz/~kevin//forDataGenomics/20171003_site/04-single-analysis/index.html#interpreting-fastqc-results

where I have in-line three screen-grab images.

**Comment by devbioinfoguy** [comment]
Kevin, sadly, the 'single analysis' and 'parallel analysis' lessons really should go away from cloud genomics, as these pages came about from a fork that someone needed early on for running their workshop. These belong in the QC / Analysis lessons.

A potentially good idea is to illustrate the differences between running a program serially or in parallel. This could be a simple exercise to show how time to compute is reduced. And/or introduce some limited parallelization capability via gnu_parallel, so show that, even if something isn't parallelized, one can use a tool to do serially things in parallel. 

Just a thought.

-B

**Comment by ACharbonneau** [comment]
I think using serial vs parallel suggested here and in https://github.com/datacarpentry/cloud-genomics/issues/14 would be a good as either: 

- part of the motivation for using the cloud
- an exercise in planning out your pipeline

If we use it for motivation, we just need a quick example of the relative speeds of serial vs parallel jobs, and how setting up parallel jobs is (usually) easier remotely.

If we use it as an exercise, we could take a general pipeline, say for RNAseq, and break it into steps. Then we would ask the learners to discuss in small groups:

- Which steps can be performed in parallel and which can't. For instance, you can clean all your fastq files in parallel, but you can't start the de novo assembly step until you have all of them cleaned, and you assemble them all at once.
- At what point do they think it becomes *more practical* to run in parallel. Is it worth the extra coding for 2 files? 10? 50? 500?
- If you're running on Amazon, where the size of the box you rent changes the price, and you have a pipeline with several parallel steps interspersed with serial steps, what should you rent? 
  - A machine large enough to handle your biggest step, that you rent the entire duration of the pipeline and holds all your data? 
  - A volume to hold all your data which you then attach to machines of varying sizes that match the steps of your pipeline? 
  - Something else?
  - What is the easiest way to go? The cheapest? The most reproducible?

**Comment by vuw-ecs-kevin** [comment]
On Fri, October 20, 2017 01:53, Bob Freeman wrote:
> Kevin, sadly, the 'single analysis' and 'parallel analysis' lessons really
> should go away from cloud genomics, as these pages came about from a fork
> that someone needed early on for running their workshop. These belong in
> the QC / Analysis lessons.

No issues with that take on things, Bob.

My point here was that taking people away to a remote site,
just to see some pictures, when the pictures could simply
be made part of the local lesson, as figures within it,
is a knock to the "self-contained" nature of a lesson.

The part of the FastQC stuff I referenced was thus just helping
to, no pun intended, paint that picture.

Presumably though, the cloud genomics lesson will need to contain
an example,  which I'd assume would be the "serial analysis" one,
but under some other episode name ?

Kevin

**Comment by devbioinfoguy** [comment]
Ah, understand, Kevin. Sorry about that. I read to fast; and clearly did not understand your intent. My apologies!

Amanda, great idea on the small breakout groups. This cloud section goes thru too quickly, and seems to be a straw lesson. More substantive thought and discussion by the learners is truly needed.
