### ISSUE TITLE
Amazon Machine Image is no longer available

### ISSUE THREAD

**Issue by tmorrell** [datacarpentry/cloud-genomics#21]
AMI ami-6516b30e doesn't seem to be available as a community image in AWS.  Searching by Carpentry also doesn't return any results.

**Comment by tracykteal** [comment]
Thanks, I just checked and it looks like it's there. It's "DataCarpentry ASPB 2015 - ami-6516b30e". You have to be in the US East (N. Virginia) region for it to appear though.

**Comment by tmorrell** [comment]
Yup, it was the region issue.  I've submitted a pull request to add the region to the lesson.  Thanks!
