### ISSUE TITLE
Image in cyverse results in Deploy_error

### ISSUE THREAD

**Issue by tmorrell** [datacarpentry/cloud-genomics#22]
The TSW Workshop Williams 1.2 image in Cyverse results in a Deploy_error.  Unfortunately the Atmosphere interface doesn't provide more details.  You can log into the instance, but itools doesn't seem to be installed.

**Comment by devbioinfoguy** [comment]
Can you please give me more info, perhaps a URL where we can track this down? Or a screen shot? The more details, the better. Feel free to attach any documents necessary. Thanks.

**Comment by tmorrell** [comment]
When I launch the instance I get a Deploy_error in the Activity comment.  Unfortunatly I can't seem to find logs that would provide more information.  I've sent Cyverse a support request, and I'll update the issue if I hear back.  

![cyverse_1](https://cloud.githubusercontent.com/assets/10798874/22847797/6225ebf6-efa4-11e6-97cf-40dd220f036f.png)

I can log into the instance, but things don't seem to be set up correctly.  For instance, iCommands are not available.  

![cyverse_2](https://cloud.githubusercontent.com/assets/10798874/22847803/648d3336-efa4-11e6-98e6-f17b86c576e4.png)

**Comment by tmorrell** [comment]
I heard back from Cyverse support - apparently the file system in the image is full and can't boot properly.  Support should have also reached out to the image owner about the problem.

**Comment by devbioinfoguy** [comment]
Thanks, Thomas. I'll contact either Jason or Tracy about this to see what we can do.

**Comment by tmorrell** [comment]
Cyverse support has fixed the issue with the TSW 1.2 image.  I have been able to complete all the lesson 1 instructions for Cyverse.
