### ISSUE TITLE
Command Line Pre-reqs?

### ISSUE THREAD

**Issue by ACharbonneau** [datacarpentry/cloud-genomics#25]
The lesson relies on Windows users having putty, but I can't find any links to download it, or instructions for setting it up properly. Other repos are directing to "Setup" pages, to get relevant software, but they're all dead links. Not sure if we need our own setup page with putty/gitbash/whatever instructions, or if this should be a broader Genomics Lesson issue. @tracykteal

**Comment by tracykteal** [comment]
I think we do need setup instructions in this lesson. I think there used to be some somewhere. I'll see if I can find where the are.

**Comment by tracykteal** [comment]
We have instructions for connecting in http://www.datacarpentry.org/cloud-genomics/03-connecting-to-remote/, but it does look like there have never been install instructions. @ACharbonneau is this something you could add? They would go in setup.md

**Comment by ACharbonneau** [comment]
I did find that bit after I posted, but I forgot to update my comment. 
I will make some instructions.
Do we want something in the main setup.md like SW does where the instructions get propagated to every workshop, or just the cloud setup?

**Comment by ACharbonneau** [comment]
Presumably, this now goes in an earlier lesson.
