### ISSUE TITLE
Add some minimal instruction on setting up an instance

### ISSUE THREAD

**Issue by ACharbonneau** [datacarpentry/cloud-genomics#27]
In episode 3, we should have some basic instructions on how to make a new instance useable. I suggest just a couple of basic commands, and where to find more information about them:

- apt-get 
- pip
- gem?
- links to where you'd find out what you can install with each

https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/03-verifying-instance.md

**Comment by ACharbonneau** [comment]
It also might be better to move this bit of instruction to https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/06-launching-your-own-instance.md

It's probably more useful to know how to update your environment when you're making a new one rather than in the middle of a pre-fab lesson.

**Comment by JasonJWilliamsNY** [comment]
I think setup of a new instance is beyond scope. However, as per the September Curriculum Advisory Committee meeting we may have a new infrastructure maintainers group and maybe this could come from them since they may have to write such content anyway.
