### ISSUE TITLE
CyVerse content

### ISSUE THREAD

**Issue by ACharbonneau** [datacarpentry/cloud-genomics#29]
The original lesson had placeholder content for CyVerse, it's still there, so we should either fill it with content or nix it. The content would be basic instructions for logging on with both Unix and PC.

https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/02-logging-onto-cloud.md

**Comment by JasonJWilliamsNY** [comment]
I can be assigned iPlant (Now CyVerse) content. This should be assigned to me for launching your own instance. Will be helpful if the relevant maintainer reached out and I can do a PR
