### ISSUE TITLE
tmux vs screen

### ISSUE THREAD

**Issue by mkuzak** [datacarpentry/cloud-genomics#30]
Is there a reason to teach `tmux` over `screen`?
I think `screen` is on most of the systems by default, `tmux` not necessarily.

**Comment by JasonJWilliamsNY** [comment]
tmux is there because its my favorite. I don't want to start a flame war over which is better, but anyway that's why its there.

**Comment by mkuzak** [comment]
I don't want to start a flame war either and I don't have a preference but I think it would good to teach most popular (and most present on remote systems) one.
