### ISSUE TITLE
PSCP?

### ISSUE THREAD

**Issue by ACharbonneau** [datacarpentry/cloud-genomics#32]
We have instructions for using what sounds like a GUI to move data around. It's called PSCP. I am 100% an Apple/UNIX person, so I don't know anything about this program. Is it still available and supported? Is there something better that we should switch it to? Last time I taught something like this, I used WinSCP, but only because it's the only one I know.

Opinions?

https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/04-data-roundtripping.md

**Comment by tracykteal** [comment]
I also don't have access to a Windows machine. The program at least still looks available and active, and PuTTY is pretty widely used. So, let's keep it this for now. We should leave this issue open to confirm on Windows later though.

**Comment by ACharbonneau** [comment]
Sounds good.

**Comment by yogesh536** [comment]
One GUI environment I would like to point out is **FileZilla** which is available for the Operating Systems:
- **Windows** (https://filezilla-project.org/download.php?type=client)
- **Linux** (https://filezilla-project.org/download.php?platform=linux), and 
- **MAC OS X 10.9 or newer** (https://filezilla-project.org/download.php?platform=osx)

It has similarities to WinSCP (Available for Windows platform and can be installed in MAC as well using Wine (https://appdb.winehq.org/objectManager.php?sClass=application&iId=1285).
