### ISSUE TITLE
iPlant

### ISSUE THREAD

**Issue by ACharbonneau** [datacarpentry/cloud-genomics#33]
In the data round-tripping section, we have instructions for moving data to/from iPlant. Two questions about this:

1. Should we teach iPlant? Is it still relevant?
        a. If so, are these instructions still correct?
2. If we have it in the round-tripping section, should we also teach how to log into it? 
        a. If so, it needs to be added to the javascript in https://github.com/datacarpentry/cloud-genomics/issues/28 and will need log-in content written.

https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/04-data-roundtripping.md

**Comment by ACharbonneau** [comment]
This is now only relevant in https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/06-launching-your-own-instance.md
I left all the instructions that were there, but it should get updated/formatted better

**Comment by JasonJWilliamsNY** [comment]
I can be assigned iPlant (Now CyVerse) content. This should be assigned to me for launching your own instance. Will be helpful if the relevant maintainer reached out and I can do a PR
