### ISSUE TITLE
Parallel analysis

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/cloud-genomics#4]
[Parallel analysis](http://www.datacarpentry.org/cloud-genomics/05-parallel-analysis/)

- [ ] write content to cover outlined lesson objectives
- [ ] why we are interested in using parallel computing is not discussed, we just dive in into how to do it

**Comment by devbioinfoguy** [comment]
Not sure that this module is needed anymore. See comments for #Issue #14

**Comment by devbioinfoguy** [comment]
If anything, I had thoughts that we could demonstrate what a serial vs parallel analysis would look like. E.g. do some small task serially, then in parallel. This might also be a good opportunity to demonstrate gnu_parallel. Or not, if that might be too much.

**Comment by ACharbonneau** [comment]
We have a lot of issues that all are asking the same basic question, and it's making it difficult to keep track of ideas.  I'm closing all the extra "parallel computing" ones and dumping them into https://github.com/datacarpentry/cloud-genomics/issues/19 to make it easier to keep track of. Please discuss there.
