### ISSUE TITLE
Installing additional software

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/cloud-genomics#49]
Installing additional software section in http://www.datacarpentry.org/cloud-genomics/03-verifying-instance/ has a placeholder: 

Add stuff about installing software! apt-get

Mention also about the fact that you can use apt-get to incorporate O/S security updates etc?

**Comment by ErinBecker** [comment]
@ACharbonneau - Could we either add some text in the placeholder section or delete this section for this release?

**Comment by ACharbonneau** [comment]
**Main issue:** Ideally,  http://www.datacarpentry.org/cloud-genomics/03-verifying-instance/ would have a short 'how to install software' segment. Maybe just apt-get-ing a tiny silly program?  Along with a mention also about the fact that you can use apt-get to incorporate O/S security updates etc? 

**Extras:** This could be expanded with other program manager tools in http://www.datacarpentry.org/cloud-genomics/LaunchingInstances/ if someone wants to write it.

**Comment by fmichonneau** [comment]
Currently the AMI isn't set up to allow dcuser to run root-level privileges commands, and the apt-get commands don't work. A paragraph should be added in the text of the lesson that reflects this.
