### ISSUE TITLE
Landing page - FIXMEs

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/cloud-genomics#5]
[Landing page](http://www.datacarpentry.org/cloud-genomics/) - add prerequisites

**Comment by ACharbonneau** [comment]
File to edit: https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/index.md

Pre-Reqs: They should have installed PuTTY already, if needed. And the need a basic understanding of the shell. I think that's it?

FIXME: home page introduction: Needs a short intro to this section. Should be similar to: https://github.com/datacarpentry/shell-genomics/blob/gh-pages/index.md

**Comment by ACharbonneau** [comment]
Fixed in https://github.com/datacarpentry/cloud-genomics/pull/46
