### ISSUE TITLE
capitalization for consistency

### ISSUE THREAD

**Issue by rdikow** [datacarpentry/cloud-genomics#56]
In "Which Cloud for my data," the below bulleted items should be capitalized to be consistent with other lessons and episodes.

However, most HPCCs (High Performance Computing Clusters) put limits on:

- the number of processors a user can utilize at once
- the amount of disk storage per user
- the amount of time a single process can run
- what programs can be installed, and by whom
- who can have accounts and access data

**Comment by dvanic** [comment]
Hi! This sounds reasonable!

Not sure if you're a newbie - would you like to fix this issue yourself by forking the repo and fixing it, and do you perhaps need a bit of help figuring out how to do this?

I can fix it myself, but just wondering if this is your first time contributing to the materials, and you'd like a bit of help?

**Comment by devbioinfoguy** [comment]
@tracykteal I'm assuming we close this issue now, yes??
