### ISSUE TITLE
Slow running AWS instances?

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/cloud-genomics#57]
One of the instructors after a recent DC Genomics workshop reported that about half the AWS instances were running significantly slower than the others.  They were all created in one bulk action, so there was no difference among them.  They were taken down before I could investigate more but I wanted to bring this up and will provide direct links if it happens again.

**Comment by tracykteal** [comment]
This happens sometimes. The only thing I've found is to start up new instances to replace the slow ones. Happy to hear if people have other solutions.

**Comment by maneesha** [comment]
Thanks @tracykteal 
We always set up extra instances for each workshop just in case of things like this.  I'll keep this issue open for now in case people have other solutions.

**Comment by ErinBecker** [comment]
See also https://github.com/datacarpentry/wrangling-genomics/issues/140 @taylorreiter's comments on switching to a different instance type to improve performance. I am looking into this option and will update this thread.
