### ISSUE TITLE
Cloud content in the schedule is out of sync with the learner

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [datacarpentry/cloud-genomics#66]
As the workshop is taught (at least the cases I have seen) there is a lot of the cloud content that comes before the shell lesson is taught. This is potentially a source of confusion. Some of the content (enough to talk about the value of cloud, give some context) could come quite early. Some of the content (emphasizing commands and data transfer) may be better appreciated after the shell lesson.

**Comment by ACharbonneau** [comment]
We've talked about this a lot (see https://github.com/datacarpentry/cloud-genomics/issues/35) and my understanding was that the November lesson push put us at the end of the lessons, as that was where most instructors were teaching it anyway

**Comment by ErinBecker** [comment]
@JasonJWilliamsNY @ACharbonneau - This has come up in a couple of different issues, so it seems like it's still a point of contention. I'll make sure this gets back on the CAC agenda for this meeting (Sept 24 and 25).

**Comment by ACharbonneau** [comment]
Thanks!

**Comment by ErinBecker** [comment]
According to the schedule on the [workshop website homepage](https://github.com/datacarpentry/wrangling-genomics/issues/140) and the first episode of [the shell lesson](https://datacarpentry.org/shell-genomics/01-introduction/), the current workflow for teaching this workshop starts with shell (and sweeps the cloud stuff under the rug) and then brings cloud back out at the end to explain what is going on. Closing this issue for now. @JasonJWilliamsNY - please reopen if this needs more clarity (in the instructors notes for example).
