### ISSUE TITLE
Can't find AWS image 

### ISSUE THREAD

**Issue by tobyhodges** [datacarpentry/cloud-genomics#82]
Based on the instructions in https://datacarpentry.org/genomics-workshop/setup.html I looked on AWS for `ami-0985860a69ae4cb3d` but couldn't find any images relating to Data Carpentry (screenshot below). Is the image no longer available for this machine?

![Screenshot 2019-04-08 at 11 04 51](https://user-images.githubusercontent.com/9694524/55725334-c3f1f700-5a0d-11e9-9c00-1cb5e4cb387e.png)

**Comment by ErinBecker** [comment]
Hi @tobyhodges - thanks for reporting this. That is the correct AMI, but apparently when searching Community AMIs, you need to specify the location you are searching in. For this AMI, that will be N. Virginia. You can select your region in the upper right hand corner of the AWS menu bar that runs across the top of each page. If you change to N. Virginia and search this AMI in Community AMIs, you should find it. I've put in a PR to address this here: https://github.com/datacarpentry/genomics-workshop/pull/71. Review for clarity would be welcome!

**Comment by tobyhodges** [comment]
Great - thank you for the info, Erin. I like the wording that you've chosen in #71.

However, if we're likely to be teaching more of these DC Genomics workshops in Europe, I think it might be good to copy the image over to one or more of the European AWS centers, as I guess that that will have (perhaps minor) effects on performance during the workshops. (See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/CopyingAMIs.html#copy-amis-across-regions.)

If we notice poor performance during the workshop in May, I'll report back.

Thanks for your help!

**Comment by ErinBecker** [comment]
Thank you @tobyhodges, I wasn't aware of the potential performance issues (although it certainly makes sense now that you mention it). I know that @aschuerch is also teaching this workshop in Europe (in fact I believe the workshop just ended). @aschuerch - did your group have any performance issues on the AMI?

**Comment by aschuerch** [comment]
No, we did not experience any performance issues. I also never experienced performance issues with the earlier AMIs which were also N.Virginia.

**Comment by ErinBecker** [comment]
Excellent! Thank you @aschuerch. I'll close this issue for now, but please @tobyhodges, if you experience any performance issues at your May workshop, feel free to raise a new issue and I'll look into AMI locations.
